name: Terraform Deploy

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:   # âœ… Manual trigger only


jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1 # change if needed

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init ec2
        run: terraform init
        working-directory: ec2

      - name: Terraform Validate ec2
        run: terraform validate
        working-directory: ec2

      - name: Terraform Plan ec2
        run: terraform plan -out=tfplan 
        working-directory: ec2

      - name: Terraform Apply ec2
        run: terraform apply -auto-approve tfplan
        working-directory: ec2
